{
  name: 'rbm_vbm',
  learning_args: {
    epochs: 1000,
    optimizer: 'sgd',
    learning_rate: 0.0001,
    l1_decay: 0.01
  },
  inference_args: {
    n_chains: 10,
    persistent: True,
    n_steps: 1
  },
  dim_h: 60,
  test_every: 10,
  dataset_args: {
    dataset: 'mri',
    source: '$data/VBM_test/VBM.yaml'
  }
}