{
  name: 'rbm_olin',
  learning_args: {
    epochs: 1000,
    optimizer: 'sgd',
    learning_rate: 0.001,
    l1_decay: 0.1
  },
  inference_args: {
    n_chains: 10,
    persistent: True,
    n_steps: 1
  },
  dim_h: 60,
  test_every: 10,
  show_every: 10,
  dataset_args: {
    dataset: 'fmri_iid',
    source: '$data/AOD/data.yaml'
  }
}